project:
  type: book
  output-dir: docs

engine: knitr

bibliography: references.bib

book:
  title: "ggplot2: Gráficos elegantes para análisis de datos (3e)"
  reader-mode: true

  page-footer:
    left: |
      ggplot2: Gráficos elegantes para análisis de datos (3e) fue escrito por
      Hadley Wickham, Danielle Navarro, y Thomas Lin Pedersen.
    right: |
      Este libro fue creado usando <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
  favicon: cover.jpg

  author:
    - name: HADLEY WICKHAM
    - name: DANIELLE NAVARRO
    - name: "&"
    - name: THOMAS LIN PEDERSEN

  search: true
  sidebar:
    pinned: true
    tools:
      - icon: github
        menu:
          - text: Original
            url: https://github.com/hadley/ggplot2-book/
          - text: Traducción
            url: https://github.com/davidrsch/ggplot2b-es
  page-navigation: true

  chapters:
    - index.qmd
    - preface-3e.qmd
    - preface-2e.qmd

    - part: start.qmd
      chapters:
        - introduction.qmd
        - getting-started.qmd

    - part: toolbox.qmd
      chapters:
        - individual-geoms.qmd
        - collective-geoms.qmd
        - statistical-summaries.qmd
        - maps.qmd
        - networks.qmd
        - annotations.qmd
        - arranging-plots.qmd

    - part: scales.qmd
      chapters:
        - scales-position.qmd
        - scales-colour.qmd
        - scales-other.qmd

    - part: mastery.qmd
      chapters:
        - layers.qmd
        - scales-guides.qmd
        - coord.qmd
        - facet.qmd
        - themes.qmd

    - part: extending.qmd
      chapters:
        - programming.qmd
        - internals.qmd
        - extensions.qmd
        - ext-springs.qmd

format:
  html:
    theme:
      - cosmo
    code-link: true
    author-meta: "Hadley Wickham, Danielle Navarro, y Thomas Lin Pedersen"
    include-after-body: [ddrsch_script.html]
    include-in-header:
      - ga_script.html
    callout-appearance: simple
    lang: es

editor: source
